DROP TABLE IF EXISTS noteful_notes;

CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    folderId INTEGER REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    modified TIMESTAMP DEFAULT now() NOT NULL
);

-- name, content, folderId, modified